<a href="https://colab.research.google.com/github/KASHISHGOGIAA/ML-LAB/blob/main/ML_Lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

x = np.array([4, 8, 13, 7])
y = np.array([11, 4, 5, 14])

data = np.column_stack((x, y))

cov_matrix = np.cov(data.T)
print("Covariance Matrix:\n", cov_matrix)

eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)

print("\nEigenvalues:\n", eigen_values)
print("\nEigenvectors:\n", eigen_vectors)

sorted_indices = np.argsort(eigen_values)[::-1]
sorted_eigenvalues = eigen_values[sorted_indices]
sorted_eigenvectors = eigen_vectors[:, sorted_indices]

print("\nSorted Eigenvalues:\n", sorted_eigenvalues)
print("\nSorted Eigenvectors:\n", sorted_eigenvectors)
exponentary data analysis,


Covariance Matrix:
 [[ 14. -11.]
 [-11.  23.]]

Eigenvalues:
 [ 6.61513568 30.38486432]

Eigenvectors:
 [[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]

Sorted Eigenvalues:
 [30.38486432  6.61513568]

Sorted Eigenvectors:
 [[ 0.55738997 -0.83025082]
 [-0.83025082 -0.55738997]]
